INSERT INTO plans (
  code,
  name,
  description,
  monthly_price,
  max_instances,
  max_users,
  daily_messages_per_instance,
  max_active_lists,
  api_access_level,
  webhooks_enabled,
  advanced_reports_enabled,
  audit_enabled,
  support_level,
  metadata
) VALUES
  (
    'ESSENTIAL',
    'Essencial',
    'Campanhas, agendamentos, relatorios basicos e API basica.',
    39.90,
    1,
    2,
    400,
    10,
    'BASIC',
    false,
    false,
    false,
    'STANDARD',
    '{"additionalInstancePrice": 19.90}'::jsonb
  ),
  (
    'PROFESSIONAL',
    'Profissional',
    'API completa, webhooks, relatorios avancados e exportacao.',
    59.90,
    2,
    5,
    600,
    NULL,
    'FULL',
    true,
    true,
    false,
    'PRIORITY',
    '{"additionalInstancePrice": 19.90}'::jsonb
  ),
  (
    'ADVANCED',
    'Avancado',
    'Permissoes avancadas, auditoria, relatorios completos e prioridade operacional.',
    89.90,
    5,
    15,
    800,
    NULL,
    'FULL',
    true,
    true,
    true,
    'PRIORITY',
    '{"additionalInstancePrice": 19.90}'::jsonb
  )
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  monthly_price = EXCLUDED.monthly_price,
  max_instances = EXCLUDED.max_instances,
  max_users = EXCLUDED.max_users,
  daily_messages_per_instance = EXCLUDED.daily_messages_per_instance,
  max_active_lists = EXCLUDED.max_active_lists,
  api_access_level = EXCLUDED.api_access_level,
  webhooks_enabled = EXCLUDED.webhooks_enabled,
  advanced_reports_enabled = EXCLUDED.advanced_reports_enabled,
  audit_enabled = EXCLUDED.audit_enabled,
  support_level = EXCLUDED.support_level,
  metadata = EXCLUDED.metadata,
  updated_at = now();
